-- Add missing suspension columns

ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason TEXT NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_expires TIMESTAMP NULL DEFAULT NULL;

-- Verify columns
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'users' AND COLUMN_NAME LIKE '%suspend%' 
ORDER BY ORDINAL_POSITION;
