<?php
// Database setup script
// Run this file once to create the database and tables

// Database configuration for setup
define('DB_HOST', 'localhost');
define('DB_NAME', 'findajob_ng');
define('DB_USER', 'root');
define('DB_PASS', '');

echo "<h2>FindAJob Nigeria - Database Setup</h2>";

try {
    // Connect to MySQL server (without database)
    $pdo = new PDO("mysql:host=" . DB_HOST . ";charset=utf8mb4", DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "<p>✓ Connected to MySQL server</p>";
    
    // Create database if it doesn't exist
    $pdo->exec("CREATE DATABASE IF NOT EXISTS " . DB_NAME . " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    echo "<p>✓ Database '" . DB_NAME . "' created/verified</p>";
    
    // Connect to the specific database
    $pdo->exec("USE " . DB_NAME);
    
    // Read and execute the schema file
    $schema = file_get_contents(__DIR__ . '/schema.sql');
    
    // Split the schema into individual statements
    $statements = array_filter(array_map('trim', explode(';', $schema)));
    
    foreach ($statements as $statement) {
        if (!empty($statement) && !preg_match('/^(--|CREATE DATABASE|USE)/i', $statement)) {
            $pdo->exec($statement);
        }
    }
    
    echo "<p>✓ Database tables created successfully</p>";
    
    // Create upload directories
    $uploadDirs = [
        '../uploads/',
        '../uploads/resumes/',
        '../uploads/logos/',
        '../uploads/profiles/'
    ];
    
    foreach ($uploadDirs as $dir) {
        if (!file_exists($dir)) {
            mkdir($dir, 0755, true);
            echo "<p>✓ Created directory: $dir</p>";
        }
    }
    
    echo "<div style='background: #d4edda; color: #155724; padding: 1rem; border-radius: 5px; margin: 1rem 0;'>";
    echo "<strong>Setup Complete!</strong><br>";
    echo "Your FindAJob Nigeria database has been set up successfully.<br>";
    echo "You can now register users and start using the application.";
    echo "</div>";
    
    echo "<p><a href='../index.php'>Go to Homepage</a></p>";
    
} catch (PDOException $e) {
    echo "<div style='background: #f8d7da; color: #721c24; padding: 1rem; border-radius: 5px; margin: 1rem 0;'>";
    echo "<strong>Setup Failed:</strong><br>";
    echo "Error: " . $e->getMessage();
    echo "</div>";
    
    echo "<h3>Troubleshooting:</h3>";
    echo "<ul>";
    echo "<li>Make sure XAMPP is running (Apache and MySQL)</li>";
    echo "<li>Check your database credentials in config/database.php</li>";
    echo "<li>Ensure the MySQL user has CREATE DATABASE privileges</li>";
    echo "</ul>";
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>FindAJob Setup</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
        h2 { color: #dc2626; }
        p { margin: 10px 0; }
        .success { color: #155724; }
        .error { color: #721c24; }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>