<?php
// Database update script for missing tables
// Run this if you get "table doesn't exist" errors

require_once '../config/database.php';

echo "<h2>FindAJob Nigeria - Database Update</h2>";
echo "<p>Adding missing tables and fixing database structure...</p>";

try {
    // Check if jobs table exists
    $stmt = $pdo->query("SHOW TABLES LIKE 'jobs'");
    $jobsTableExists = $stmt->rowCount() > 0;
    
    if (!$jobsTableExists) {
        echo "<p>📝 Adding jobs table and related structures...</p>";
        
        // Read the complete schema
        $schema = file_get_contents(__DIR__ . '/schema.sql');
        
        // Extract only the new table creation statements
        $newTables = [
            'job_categories',
            'jobs', 
            'job_applications',
            'cvs'
        ];
        
        // Split schema into statements
        $statements = explode(';', $schema);
        
        foreach ($statements as $statement) {
            $statement = trim($statement);
            if (empty($statement) || strpos($statement, '--') === 0) {
                continue;
            }
            
            // Check if this statement creates one of our new tables
            foreach ($newTables as $table) {
                if (strpos($statement, "CREATE TABLE $table") !== false) {
                    try {
                        $pdo->exec($statement);
                        echo "<p>✅ Created table: $table</p>";
                    } catch (PDOException $e) {
                        echo "<p>⚠️  Table $table might already exist: " . $e->getMessage() . "</p>";
                    }
                    break;
                }
            }
            
            // Insert sample data for job categories
            if (strpos($statement, "INSERT INTO job_categories") !== false) {
                try {
                    $pdo->exec($statement);
                    echo "<p>✅ Inserted sample job categories</p>";
                } catch (PDOException $e) {
                    echo "<p>⚠️  Job categories might already exist: " . $e->getMessage() . "</p>";
                }
            }
        }
        
        echo "<div style='background: #d4edda; color: #155724; padding: 1rem; border-radius: 5px; margin: 1rem 0;'>";
        echo "<strong>Database Updated Successfully!</strong><br>";
        echo "All missing tables have been added. You can now use the full job posting and application features.";
        echo "</div>";
        
    } else {
        echo "<div style='background: #cce5ff; color: #004085; padding: 1rem; border-radius: 5px; margin: 1rem 0;'>";
        echo "<strong>Database is Up to Date!</strong><br>";
        echo "All required tables already exist.";
        echo "</div>";
    }
    
    // Show current tables
    echo "<h3>Current Database Tables:</h3>";
    $stmt = $pdo->query("SHOW TABLES");
    $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    echo "<ul>";
    foreach ($tables as $table) {
        echo "<li>✅ $table</li>";
    }
    echo "</ul>";
    
    echo "<p><a href='../index.php' style='background: #dc2626; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>Go to Homepage</a></p>";
    echo "<p><a href='../pages/company/dashboard.php' style='background: #059669; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin-left: 10px;'>Test Employer Dashboard</a></p>";
    
} catch (PDOException $e) {
    echo "<div style='background: #f8d7da; color: #721c24; padding: 1rem; border-radius: 5px; margin: 1rem 0;'>";
    echo "<strong>Update Failed:</strong><br>";
    echo "Error: " . $e->getMessage();
    echo "</div>";
    
    echo "<h3>Troubleshooting:</h3>";
    echo "<ul>";
    echo "<li>Make sure XAMPP is running (Apache and MySQL)</li>";
    echo "<li>Check your database connection in config/database.php</li>";
    echo "<li>Try running the main setup.php first</li>";
    echo "</ul>";
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>FindAJob Database Update</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 50px auto; 
            padding: 20px; 
            background: #f8fafc;
        }
        h2 { color: #dc2626; }
        p { margin: 10px 0; }
        .success { color: #155724; }
        .error { color: #721c24; }
        ul { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        li { padding: 5px 0; }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>